#include <stdio.h>

int main()
{
	char c;

	c = 'A';
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n",c, c, c,c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);

	c = 'a';
	printf("\n\n\n%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d,%c의 16진수 코드값은 %x\n", c, c, c, c);

	c = '0';
	printf("\n\n\n%c의 십진수 코드값은 %d, %c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d, %c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d, %c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d, %c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d, %c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d, %c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d, %c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d, %c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d, %c의 16진수 코드값은 %x\n", c, c, c, c);
	c = c + 1;
	printf("%c의 십진수 코드값은 %d, %c의 16진수 코드값은 %x\n", c, c, c, c);

	return 0;
}